apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TENANT-pets-portal
spec:
  destination:
    name: ''
    namespace: TENANT
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://alyibrahim.github.io/helm-repo'
    targetRevision: 0.1.0
    chart: pets-portal
    helm:
      parameters:
        - name: replicaCount
          value: "2"
        - name: service.type
          value: ClusterIP
        - name: ingress.enabled
          value: "true"
        - name: ingress.baseDomain
          value: BASE_DOMAIN
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

